import LanguageSwitcher from "@/components/language-switcher";
import { ThemeProvider } from "@/components/theme-provider";
import { LayoutProvider } from "@/hooks/use-layout";
import { META_THEME_COLORS } from "@/lib/config";
import { i18n } from "@/lib/i18n";
import "@/styles/globals.css";
import { defineI18nUI } from 'fumadocs-ui/i18n';
import { RootProvider } from 'fumadocs-ui/provider/next';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const { provider } = defineI18nUI(i18n, {
  translations: {
    es: {
      displayName: "Español"
    },
    en: {
      displayName: "English"
    },
  },
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  params: Promise<{ lang: string }>;
  children: React.ReactNode;
}) {
  const lang = (await params).lang;

  return (
    <html lang={lang} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || ((!('theme' in localStorage) || localStorage.theme === 'system') && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.querySelector('meta[name="theme-color"]').setAttribute('content', '${META_THEME_COLORS.dark}')
                }
                if (localStorage.layout) {
                  document.documentElement.classList.add('layout-' + localStorage.layout)
                }
              } catch (_) {}
            `,
          }}
        />
        <meta name="theme-color" content={META_THEME_COLORS.dark} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootProvider
          i18n={provider(lang)}
        >
          <ThemeProvider>
            <LayoutProvider>
              <LanguageSwitcher />
              {children}
            </LayoutProvider>
          </ThemeProvider>
        </RootProvider>
      </body>
    </html>
  );
}
